"""name or category check fixed

Revision ID: 080b860b79a7
Revises: ae1d12c7ab25
Create Date: 2026-08-21 12:55:29.877275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080b860b79a7'
down_revision = 'ae1d12c7ab25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_check_constraint('req_reps_or_sets', 'reps IS NOT NULL OR sets IS NOT NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_constraint('req_reps_or_sets', type_='check')

    # ### end Alembic commands ###
