"""constraints added

Revision ID: ae1d12c7ab25
Revises: b5f72f7e3103
Create Date: 2026-08-20 21:04:37.316783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1d12c7ab25'
down_revision = 'b5f72f7e3103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_unique_constraint('exercise_name_unique', ['name'])

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('exercise_name_unique', type_='unique')

    # ### end Alembic commands ###
