"""table_args fixed

Revision ID: c343f2e90a08
Revises: 080b860b79a7
Create Date: 2026-08-21 12:59:18.328407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c343f2e90a08'
down_revision = '080b860b79a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_check_constraint('req_name_or_category', 'NOT (name IS NULL AND category IS NULL)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('req_name_or_category', type_='check')

    # ### end Alembic commands ###
